server:
  port: 8100
  servlet:
    context-path: /api
spring:
  jpa:
    show-sql: true
    hibernate: 
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.H2Dialect
  datasource: 
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
